---
title: '2.1 : 2 locus / 2 allele models'
---

### Background and assumptions

- Discrete generations
- Recombination occurs at the rate $r$, where $r \in [0, \frac{1}{2}]$
- Diploid population with 2 loci, $A$ and $B$, each with 2 alleles, $1$ and $2$
- There is no fitness effect due to an allele's relative position on the chromosome, e.g. $A_1 B_1 + A_2 B_2$ has the same fitness as $A_1 B_2 + A_2 B_1$
    - *$i$ and $j$ are unordered/interchangeable*

Let $x_1$, $x_2$, $x_3$, and $x_4$ represent the frequencies of the four gametes, $A_1 B_1$, $A_1 B_2$, $A_2 B_1$, and $A_2 B_2$, respectively
    - $\sum_{i=1}^4 x_i = 1$

Linkage disequilibrium is given by $D = x_1 x_4 - x_2 x_3$, i.e. the difference between the frequency products of $A_1 B_1$ $A_2 B_2$ and $A_1 B_2$ $A_2 B_1$


### Relative and mean fitnesses

- Each combination of two gametes has a fixed fitness, $W_{ij} = W_{ji}$
- The $i$ and $j$ correspond to the subscripts of the corresponding gametes used for the gamete frequencies $x_k$; $k = 1, 2, 3, 4$
    - e.g. $A_1 A_2$ and $B_1 B_2$ correspond to the gametes $A_1 B_1$ and $A_2 B_2$, which have respective frequencies of $x_1$ and $x_4$, so the zygote has fitness $W_{14}$

The two-allele system's zygotic fitnesses are described the following matrix,

$$
    \bf{W} = \begin{bmatrix}
                             W_{11} & W_{12} & W_{12} & W_{22} \\
                             W_{13} & W_{14} & W_{14} & W_{24} \\
                             W_{13} & W_{14} & W_{14} & W_{24} \\
                             W_{33} & W_{34} & W_{34} & W_{44}
             \end{bmatrix},
$$

where the rows are for the gametes $A_1 A_1, A_1 A_2, A_2 A_1, A_2 A_2$, respectively, and likewise the columns are the same order of gametes for locus $B$.

Since $W_{ij} = W_{ji}$, this matrix reduces to

$$
    \bf{W} = \begin{bmatrix}
                             W_{11} & W_{12} & W_{22} \\
                             W_{13} & W_{14} & W_{24} \\
                             W_{33} & W_{34} & W_{44}
             \end{bmatrix},
$$

where the rows and columns are for the gametes $A_1 A_1, A_1, A_2, A_2 A_2$ and $B_1 B_1, B_1 B_2, B_2 B_2$, respectively.

The marginal fitness of each gamete in a given generation is the average of the fitness of the four zygotes containing the gamete, weighted by the frequency of the other gamete in the pair:
$$W_i = \sum_{j=1}^4 W_{ij} x_j; \quad i = 1, 2, 3, 4$$

We can then calculate the mean fitness of the population by taking the average marginal fitness of each gamete, weighted by its frequency:
$$\bar{W} = \sum_{i, j = 1}^4 W_{ij} x_i x_j = \sum_{i=1}^4 W_i x_i; \quad i, j = 1, 2, 3, 4$$


### Frequencies after one generation of selection

The frequency of a particular zygote after a generation of selection, $X'_{ij}$, is given by the fitness of the zygote weighted by the frequency of zygote divided by the mean fitness,
$$X'_{ij} = \frac{W_{ij} x_i x_j}{\bar{W}}$$

*For the next few equations, we are back to $i$ and $j$ are **alleles**.*

Recall from Chapter 1, Section 7 that the frequency of the gamete $A_i B_j$ in the next generation is given by
$$P'_{ij} = (1 - r) P_{ij} + r p_i q_i.$$

Linkage disequilibrium between the $A_i$ and $B_j$ alleles is given by
$$D_{ij} = P_{ij} - p_i q_i.$$

Therefore, it follows that
$$P'_{ij} = P_{ij} - r P_{ij} + r p_i q_j = P_{ij} - r(P_{ij} - p_i q_j) = P_{ij} - r D_{ij}.$$

*Now, back to $i$ and $j$ as **gametes**.* This translates to
$$x'_i = x_i - r D_i.$$

Recall that $D = x_1 x_4 - x_2 x_3 = D_{1} = -D_{2} = -D_{3} = D_{4}$.

Thus, in the next generation, the gamete frequencies are

$$\bar{W} x'_1 = x_1 W_1 + r W_{14} D,$$
$$\bar{W} x'_2 = x_2 W_2 - r W_{14} D,$$
$$\bar{W} x'_3 = x_3 W_3 - r W_{14} D,$$
$$\bar{W} x'_4 = x_4 W_4 + r W_{14} D.$$

At equilibrium allele frequencies, the change in $x_i$ each generation is 0, so

$$\bar{W} x'_i = x_i = x_i W_i \pm r W_{14} D.$$


## Additive fitness

Assume that the gametes at each loci contribute the following fitnesses,

| Genotype  | Fitness  |
|:---------:|:--------:|
| $A_1 A_1$ | $a_{11}$ |
| $A_1 A_2$ | $a_{12}$ |
| $A_2 A_2$ | $a_{22}$ |
| $B_1 B_1$ | $b_{11}$ |
| $B_1 B_2$ | $b_{12}$ |
| $B_2 B_2$ | $b_{22}$ |

If these fitness effects add to deterine the fitness of a zygote, then the fitness matrix is given by

$$
    \bf{W} = \begin{bmatrix}
                             W_{11} & W_{12} & W_{22} \\
                             W_{13} & W_{14} & W_{24} \\
                             W_{33} & W_{34} & W_{44}
             \end{bmatrix} =
             \begin{bmatrix}
                        a_{11} + b_{11} & a_{11} + b_{12} & a_{11} + b_{22} \\
                        a_{12} + b_{11} & a_{12} + b_{12} & a_{12} + b_{22} \\
                        a_{22} + b_{11} & a_{22} + b_{12} & a_{22} + b_{22}
             \end{bmatrix}.
$$

Let $p$ and $q$ represent allele frequencies of $A$ and $B$, respectively, such that

$$p_1 = Freq(A_1) = x_1 + x_2,$$
$$p_2 = Freq(A_2) = x_3 + x_4,$$
$$q_1 = Freq(B_1) = x_1 + x_3,$$
$$q_2 = Freq(B_2) = x_2 + x_4.$$

### Single-locus fitness

Using the equation for mean zygotic fitness $\bar{W}$ and the fitness matrix $\bf{W}$, we get

$$\bar{W} = \bar{a} + \bar{b} = \sum_{i, j = 1}^4 W_{ij} x_i x_j = \sum_{j=1}^4 W_{1,j} x_1 x_j + \sum_{j=2,4}^4 W_{2,j} x_2 x_j + \sum_{j=3,4}^4 W_{3,j} x_3 x_j + W_4 x_4^2,$$

where $\bar{a}$ and $\bar{b}$ are the mean fitnesses at each locus.

Substituting $W_{ij}$ in terms of $a$ and $b$ terms and expanding the summations, we get

$$
    \begin{eqnarray}
                     \bf{W} &=& a_{11} (x_1^2 + 2 x_1 x_2 + x_2^2) + 2 a_{12} (x_1 x_3 + x_1 x_4 + x_2 x_3 + x_2 x_4) + a_{22} (x_3^2 + 2 x_3 x_4 + x_4^2) \nonumber \\
                            &+& b_{11} (x_1^2 + 2 x_1 x_3 + x_3^2) + 2 b_{12} (x_1 x_2 + x_1 x_4 + x_2 x_3 + x_3 x_4) + b_{22} (x_2^2 + 2 x_2 x_4 + x_4^2) \nonumber
    \end{eqnarray}.
$$

Since $p_1^2 = x_1^2 + 2 x_1 x_2 + x_2^2$, and so on,

$$
    \begin{eqnarray}
                     \bf{W} = \bar{a} + \bar{b} &=& a_{11} p_1^2 + 2 a_{12} p_1 p_2 + a_{22} p_2^2 \nonumber \\
                                                &+& b_{11} q_1^2 + 2 b_{12} q_1 q_2 + b_{22} q_2^2 \nonumber
    \end{eqnarray}.
$$

### Allele frequency changes

Let us now look at the changes in allele frequencies in a generation, $\delta p_i$ or $\delta q_i$.

Recall that $\bar{W} x'_i = W_i x_i \pm r W_{14} D$. We see that the recombination term disappears. For example, consider the case of allele $p_1 = x_1 + x_2$:

$$\bar{W} x'_1 = W_1 x_1 + r W_{14} D,$$
$$\bar{W} x'_2 = W_2 x_2 - r W_{14} D.$$

The second term subtracts away and we get

$$\bar{W} p'_1 = \bar{W} (x'_1 + x'_2) = W_1 x_1 + W_2 x_2,$$

$$\delta p_1 = p'_1 - p_1 = \frac{W_1 x_1 + W_2 x_2}{\bar{W}} - (x_1 + x_2).$$

$\rightarrow$ **We see that this mirrors a case of four independent alleles with one locus, and so the Fundamental Theorem of Natural Selection holds. Accordingly, $\delta \bar{W} \ge 0$.**
